FROM openjdk:17-jdk-slim

RUN apt-get update && apt-get install -y \
    x11-apps \
    xauth \
    libxext6 \
    libxrender1 \
    libxtst6 \
    libxt6 \
    libx11-6 \
    && rm -rf /var/lib/apt/lists/*

ENV DISPLAY=host.docker.internal:0

COPY calc.jar /app/calc.jar

WORKDIR /app

CMD ["java", "-jar", "calc.jar"]